# Concatenation

In [1]:
import numpy as np

### concatenate

In [3]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y]))

[1 2 3 3 2 1]


In [4]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [5]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
print(grid)

[[1 2 3]
 [4 5 6]]


In [6]:
print(np.concatenate([grid, grid]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [7]:
print(np.concatenate([grid, grid], axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


### vstack

In [8]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])
print(np.vstack([x, grid]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [9]:
y = np.array([[99], [99]])
print(np.hstack([grid, y]))

[[ 9  8  7 99]
 [ 6  5  4 99]]
