# Creating

In [1]:
import numpy as np

### zeros

In [2]:
print(np.zeros(10, dtype=int))

[0 0 0 0 0 0 0 0 0 0]


### ones

In [3]:
print(np.ones((3, 5), dtype=float))

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


### full

In [4]:
print(np.full((3, 5), 3.14))

[[ 3.14  3.14  3.14  3.14  3.14]
 [ 3.14  3.14  3.14  3.14  3.14]
 [ 3.14  3.14  3.14  3.14  3.14]]


### arange

In [5]:
print(np.arange(0, 20, 2))

[ 0  2  4  6  8 10 12 14 16 18]


### linspace

In [6]:
print(np.linspace(0, 1, 9))

[ 0.     0.125  0.25   0.375  0.5    0.625  0.75   0.875  1.   ]


### random

* uniformly distributed
* values between 0 and 1

In [7]:
print(np.random.random((3, 3)))

[[ 0.69088606  0.23069834  0.17404469]
 [ 0.19362847  0.38273096  0.94788903]
 [ 0.3388616   0.99755517  0.97145586]]


### normal

* normally distributed
* mean: 0
* standard deviation: 1

In [8]:
print(np.random.normal(0, 1, (3, 3)))

[[-1.6121057  -0.0098206  -0.36558053]
 [-1.09125235  2.15304143  0.60199833]
 [ 0.2043695  -0.60415042 -0.65345856]]


### randint

In [9]:
print(np.random.randint(0, 10, (3, 3)))

[[1 6 2]
 [5 3 4]
 [8 5 4]]


### eye

* identity matrix

In [10]:
print(np.eye(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### empty

* uninitialized array

In [11]:
print(np.empty(3))

[ 1.  1.  1.]
