# Splitting

In [1]:
import numpy as np

### split

In [11]:
x = np.arange(10)
print(np.split(x, 5))

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [9]:
x = np.arange(10)
print(np.split(x, [3, 5, 6, 10]))

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8, 9]), array([], dtype=int64)]


In [12]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
print(np.split(x, [3, 5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


### vsplit

In [13]:
grid = np.arange(16).reshape((4, 4))
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [14]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


### hsplit

In [15]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
