# Broadcasting

In [1]:
import numpy as np

In [4]:
M = np.ones((3, 3), dtype=int)
print(M)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
print(M + 10)

[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [8]:
a = np.arange(3)
print(a)

[0 1 2]


In [9]:
print(M * a)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [11]:
b = np.arange(3).reshape(3, 1)
print(b)

[[0]
 [1]
 [2]]


In [12]:
print(M * b)

[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [13]:
print(a + b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
