# Attributes

In [1]:
import numpy as np

In [26]:
np.random.seed(0)
x1 = np.random.randint(10, size=3)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))
print(x1)
print()
print(x2)
print()
print(x3)

[5 0 3]

[[3 7 9 3]
 [5 2 4 7]
 [6 8 8 1]]

[[[6 7 7 8 1]
  [5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]]

 [[3 3 7 0 1]
  [9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]]

 [[8 4 1 4 9]
  [8 1 1 7 9]
  [9 3 6 7 2]
  [0 3 5 9 4]]]


### dtype

In [14]:
print(x1.dtype)
print(x2.dtype)
print(x3.dtype)

int64
int64
int64


### ndim

In [15]:
print(x1.ndim)
print(x2.ndim)
print(x3.ndim)

1
2
3


### shape

In [16]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(3,)
(3, 4)
(3, 4, 5)


### itemsize

In [19]:
print(x1.itemsize)
print(x2.itemsize)
print(x3.itemsize)

8
8
8


### nbytes

In [21]:
print(x1.nbytes)
print(x2.nbytes)
print(x3.nbytes)

24
96
480
