# Reshaping

In [2]:
import numpy as np

In [3]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### reshape

In [4]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [6]:
x.reshape((3, 1))
print(x)

[1 2 3]


In [7]:
print(x.reshape((3, 1)))

[[1]
 [2]
 [3]]


### newaxis

In [8]:
print(x[np.newaxis, :])

[[1 2 3]]


In [9]:
print(x[:, np.newaxis])

[[1]
 [2]
 [3]]
