# Universal Functions

In [2]:
import numpy as np

### Basic Function

In [6]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(-x)

[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [8]:
print(x + 5)

[ 5  6  7  8  9 10 11 12 13 14]


In [9]:
print(x - 5)

[-5 -4 -3 -2 -1  0  1  2  3  4]


In [10]:
print(x * 2)

[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
print(x / 2)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5]


In [12]:
print(x // 2)

[0 0 1 1 2 2 3 3 4 4]


In [13]:
print(x ** 2)

[ 0  1  4  9 16 25 36 49 64 81]


In [14]:
print(x % 2)

[0 1 0 1 0 1 0 1 0 1]


### Absolute Function

In [5]:
print(np.absolute(x))

[0 1 2 3 4 5 6 7 8 9]


In [17]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
print(x)

[ 3.-4.j  4.-3.j  2.+0.j  0.+1.j]


In [18]:
print(np.abs(x))

[ 5.  5.  2.  1.]


### Trigonometric Functions¶

In [21]:
theta = np.linspace(0, np.pi, 10)
print(theta)

[ 0.          0.34906585  0.6981317   1.04719755  1.3962634   1.74532925
  2.0943951   2.44346095  2.7925268   3.14159265]


In [22]:
print(np.sin(theta))

[  0.00000000e+00   3.42020143e-01   6.42787610e-01   8.66025404e-01
   9.84807753e-01   9.84807753e-01   8.66025404e-01   6.42787610e-01
   3.42020143e-01   1.22464680e-16]


In [23]:
print(np.cos(theta))

[ 1.          0.93969262  0.76604444  0.5         0.17364818 -0.17364818
 -0.5        -0.76604444 -0.93969262 -1.        ]


In [24]:
print(np.tan(theta))

[  0.00000000e+00   3.63970234e-01   8.39099631e-01   1.73205081e+00
   5.67128182e+00  -5.67128182e+00  -1.73205081e+00  -8.39099631e-01
  -3.63970234e-01  -1.22464680e-16]


### Exponents Function

In [26]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
print(np.exp(x))

[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03
   2.98095799e+03   8.10308393e+03]


In [28]:
print(np.exp2(x))

[   1.    2.    4.    8.   16.   32.   64.  128.  256.  512.]


In [29]:
print(np.power(3, x))

[    1     3     9    27    81   243   729  2187  6561 19683]


### Logarithms Function

In [30]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
print(np.log(x))

[       -inf  0.          0.69314718  1.09861229  1.38629436  1.60943791
  1.79175947  1.94591015  2.07944154  2.19722458]


/Users/DannyShau/anaconda/envs/py3.5/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [32]:
print(np.log2(x))

[       -inf  0.          1.          1.5849625   2.          2.32192809
  2.5849625   2.80735492  3.          3.169925  ]


/Users/DannyShau/anaconda/envs/py3.5/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


In [33]:
print(np.log10(x))

[       -inf  0.          0.30103     0.47712125  0.60205999  0.69897
  0.77815125  0.84509804  0.90308999  0.95424251]


/Users/DannyShau/anaconda/envs/py3.5/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.
