# Indexing

In [1]:
import numpy as np

In [6]:
np.random.seed(0)
x1 = np.random.randint(10, size=3)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [7]:
print(x1)

[5 0 3]


In [8]:
print(x1[0])

5


In [9]:
print(x1[-1])

3


In [11]:
print(x2)

[[3 7 9 3]
 [5 2 4 7]
 [6 8 8 1]]


In [10]:
print(x2[0, 0])

3


In [13]:
x2[0, 0] = 0
print(x2)

[[0 7 9 3]
 [5 2 4 7]
 [6 8 8 1]]


In [15]:
x2[0, 0] = 3.14 # truncated
print(x2)

[[3 7 9 3]
 [5 2 4 7]
 [6 8 8 1]]
