# Selection

In [1]:
import numpy as np
import pandas as pd

In [2]:
area = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
print(data)

              area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193


In [3]:
print(data['area'])

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64


In [4]:
print(data.area)

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64


In [5]:
print(data.area is data['area'])

True


In [6]:
print(data.pop is data['pop'])

False


In [7]:
data['density'] = data['pop'] / data['area']
print(data)

              area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740


In [8]:
print(data.values)

[[  4.23967000e+05   3.83325210e+07   9.04139261e+01]
 [  1.70312000e+05   1.95528600e+07   1.14806121e+02]
 [  1.49995000e+05   1.28821350e+07   8.58837628e+01]
 [  1.41297000e+05   1.96511270e+07   1.39076746e+02]
 [  6.95662000e+05   2.64481930e+07   3.80187404e+01]]


In [9]:
print(data.T)

           California       Florida      Illinois      New York         Texas
area     4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05  6.956620e+05
pop      3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07  2.644819e+07
density  9.041393e+01  1.148061e+02  8.588376e+01  1.390767e+02  3.801874e+01


In [10]:
print(data.values[0])

[  4.23967000e+05   3.83325210e+07   9.04139261e+01]


In [11]:
print(data['area'])

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64


In [12]:
print(data.loc[:'Illinois', :'pop'])

              area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135


In [13]:
print(data.iloc[:3, :2])

              area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135


In [15]:
print(data.loc[data.density > 100, ['pop', 'density']])

               pop     density
Florida   19552860  114.806121
New York  19651127  139.076746


In [16]:
data.iloc[0, 2] = 90
print(data)

              area       pop     density
California  423967  38332521   90.000000
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740


In [17]:
print(data['Florida':'Illinois'])

            area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763


In [18]:
print(data[1:3])

            area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763


In [19]:
print(data[data.density > 100])

            area       pop     density
Florida   170312  19552860  114.806121
New York  141297  19651127  139.076746


In [23]:
print(data[data['density'] > 100])

            area       pop     density
Florida   170312  19552860  114.806121
New York  141297  19651127  139.076746


In [25]:
try:
    print(data[data['Florida'] < 1000])
except:
    data2 = data.T
    print(data2[data2['Florida'] < 1000])

         California     Florida   Illinois    New York     Texas
density        90.0  114.806121  85.883763  139.076746  38.01874
